#! /bin/sh

sxhkd &
xwallpaper --maximize ~/pictures/wallpaper
wmname LG3D &
#bar.sh &

bspc monitor HDMI-0 -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII IX X

bspc config border_width            5
bspc config normal_border_color     \#2c2e34
bspc config focused_border_color    \#76cce0
bspc config focus_follows_pointer   true
bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
#bspc config top_padding             15
bspc config window_gap              15

##Windows Rules
bspc config automatic_scheme longest_side
bspc rule -a Zathura state=tiled
